### ISSUE TITLE
Ubuntu script failing due to invalid link 

### ISSUE THREAD

**Issue by chaudhryaziz** [railsgirls/installation-scripts#33]
When executing the Ubuntu script in Ubuntu Mate 15.04 the script fails due to the fact that the following line: 

sudo add-apt-repository ppa:chris-lea/node.js

will add an invalid entry under Ubuntu 15.04 and thus running sudo apt-get update will fail. 

Furthermore, for new users this may cause confusion as now there is an invalid entry whenever sudo apt-get update is performed that the user may not know how to remove. 

As a result, maybe we can add a check to ensure the repository is valid before adding it?

**Comment by craysiii** [comment]
Just ran into this issue when creating a new 15.04 VM. Interesting because I had used this method in two other instances on 15.04 and did not have any problems then. 

All I need is an up-to-date version of node.js, correct? I will try to find a different PPA or source, and remove the offending line when I run it again.

**Comment by craysiii** [comment]
I got it to work, which can be seen in my latest commit b843ed57aff8be5474b3c94a98c9d765781207f7. I noticed that the script wanted to use curl before installing it, so I fixed that as well.

Not sure if I should make a pull-request or not.
